### PR TITLE
Cleanup TPB proxy list

### PR DESCRIPTION
**Pull request by jamesmacwhite**
### Description of what this fixes:

A lot of the TPB proxy sites currently listed are dead, causing ConnectionError traceback events to raised in the DEBUG log. I've been through the current list and removed the dead ones. Here's the status report of the proxy sites identified as dead/not working. The one's remaining are still working.

```
https://thepiratebay.mn (NXDOMAIN)
https://thepiratebay.gd (NXDOMAIN)
https://thepiratebay.la (NXDOMAIN)
https://piratebay.host (NXDOMAIN)
https://thepiratebay.expert (ERR_CONNECTION_TIMED_OUT)
https://pirate.guru (ERR_CONNECTION_TIMED_OUT)
https://tpb.ninja (Loads a page with a proxy list not TPB directly)
https://thehiddenbay.me (HTTP STATUS 502/HSTS SSL Error)
https://ukunlocked.com (ERR_TUNNEL_CONNECTION_FAILED)
https://tpb.freed0m4all.net (ERR_TUNNEL_CONNECTION_FAILED)
https://piratebays.eu (ERR_TUNNEL_CONNECTION_FAILED)
https://thepiratebayz.com (ERR_TUNNEL_CONNECTION_FAILED)
https://zaatoka.eu (ERR_TUNNEL_CONNECTION_FAILED)
https://piratemirror.net (ERR_TUNNEL_CONNECTION_FAILED)
https://torrentdr.com (ERR_TUNNEL_CONNECTION_FAILED)
https://www.cleantpbproxy.com (ERR_TUNNEL_CONNECTION_FAILED)
```

For tpb.ninja, this just loads a page with a proxy list and is a proxy of https://proxybay.one/ itself, so I don't think it belongs in this list either?

**Update 11/03/2017:**

As this PR has been sitting idle for a while, I've just gone through the remaining proxy sites again to confirm all are still working, in addition the following have been removed:

```
https://pirateproxy.sx - SSL error, cert mismatch, looks like site is dead
https://tpbproxy.co - Redirects to https://pirateproxy.vip and fails ERR_TUNNEL_CONNECTION_FAILED
```

*Less critical warnings:*

```
https://thepiratebay.uk.net - Triggers harmful/malware protection in Firefox/Chrome
https://theproxypirate.pw - Triggers harmful/malware protection in Firefox/Chrome
```

These should be OK for use still as the malware protection is browser specific shouldn't cause any issues making requests via Python.

### CODE REVIEW

**Comment by dere** [comment]
This needs to be merged, literally zero of the TBP mirrors work as-is.

Additionally, thepiratebay.org could be added. #7000 supposedly does this but that PR has way too many commits.

**Comment by jamesmacwhite** [comment]
@dere That's correct. You can override the `thepiratebay[domain]` field with the primary TPB domain, this works fine for anyone who either doesn't have their ISP block The Pirate Bay domains or uses a VPN to avoid it, therefore avoiding the issue of hitting a "dead" proxy site in the array.

A lot of the TPB proxy sites listed in CP are dead, a few more can probably be added in addition to counter it as well.

Its up to the project collaborators to merge.

**Comment by jamesmacwhite** [comment]
@RuudBurger Could this potentially pushed to develop? I think this cleanup is becoming more critical, given the amount of "dead" proxy sites.

**Comment by RuudBurger** [comment]
Thanks!

**Pull request merged**
