### PR TITLE
correct ETA issue and display more info regarding ETA

### PR DESCRIPTION
**Pull request by geogolem**
### Description of what this fixes:
This displays more information regarding release dates and ETA's so that people can better see what is going on. There is also some changes to bypass the couchpotato api and use omdb api direcly to grab eta dates since couchpotato API seems to be wrong. 

### Related issues:
...

### CODE REVIEW

**Comment by RuudBurger** [comment]
Please merge it agains the latest develop branch. Thanks!

**Comment by geogolem** [comment]
i am quite sure I did merge it against the develop branch... this is the second time i tried. please let me know what I am doing wrong.

**Comment by geogolem** [comment]
it does show: "geogolem  wants to merge 287 commits into CouchPotato:develop from geogolem:develop"

so i dont know what you mean?

**Comment by RuudBurger** [comment]
The merge should not contain 287 commits ;)
If you see https://github.com/CouchPotato/CouchPotatoServer/pull/7113/files it also tries to change stuff to what's on the master branch.

- Checkout the develop branch
- Apply your changes
- Push to your develop branch (or beter, create a new branch develop_eta_fixes for example)
- Make the PR through github

**Comment by dozyh** [comment]
Did the ETA issue get fixed? I don't see a new PR referenced.

**Comment by geogolem** [comment]
@dozyh : I have initiated another pull request here along with some other changes: https://github.com/CouchPotato/CouchPotatoServer/pull/7126

**Pull request closed without merging**
