### PR TITLE
Yts provider 720p 1080p (Revision - Fix)

### PR DESCRIPTION
**Pull request by Swkgram**
### Description of what this fixes:
When searching for Avatar 4 (2022) it found Avatar (2009) releases.
I added a name check on the releases the provider finds. Also increasing the limit of results it may parse, just to be sure it won't miss a release.

@ward0 found this bug and reported it on my original pull request #7186

### Limitations
Same limitations as mentioned in #7186 

### Testing
Tested the Avatar problem and it was fixed.  
Tested with Deadpool (2016) and Deadpool 2 (2018) - working.

### CODE REVIEW

**Comment by ward0** [comment]
Cool thanks, happy to help.

**Comment by gchaimovitz** [comment]
Hi, I'm receiving this error in the logs after merging your changes.  Thoughts?

[ couchpotato.core.event] Error in event "provider.search.torrent_magnet.movie", that wasn't caught: Traceback (most recent call last): File "C:\CouchPotatoServer\couchpotato\core\event.py", line 15, in runHandler return handler(*args, **kwargs) File "C:\CouchPotatoServer\couchpotato\core\media\_base\providers\base.py", line 229, in search self._search(media, quality, results) File "C:\CouchPotatoServer\couchpotato\core\media\_base\providers\torrent\yts.py", line 28, in _search log.error('%s returned an error (search or tryInt() failed): %s', (self.getName(), data['error'])) KeyError: 'error' encoding=cp1252 debug=False args=[]

**Comment by matansh** [comment]
Tested your code using wonder woman 2017
(stopped CP > overwritten yts.py in /couchpotato/core/media/_base/providers/torrent/ using the code from this PR > rm yts.pyc > started CP)

it still found releases of wonder woman 2009 but as you said avatar 2 and deadpool 2 work like a charm (no errors in my log)

**Comment by Swkgram** [comment]
@matansh Thanks mate, should be fixed now.

@gchaimovitz I merged it myself, but couldn't reproduce the error.
My thoughts, when calling:

    log.error('%s returned an error (search or tryInt() failed): %s', (self.getName(), data['error']))

The dictionary called `data` doesn't contain the key `'error'`

**Comment by RuudBurger** [comment]
Thanks again!

**Pull request merged**
