### PR TITLE
Fix iptorrents.py

### PR DESCRIPTION
**Pull request by swordfish6975**
IP torrents now needs a cookie to work properly.

### Description of what this fixes:
...

### Related issues:
...

### CODE REVIEW

**Comment by emq** [comment]
@RuudBurger can we have this merged please? 🙏 without it iptorrents support is simply broken (due to recaptcha on login page)

**Comment by lgreerduo** [comment]
Any update on this by chance? I only use IPTorrents and CouchPotato is pretty useless if the only downloader is borked.

**Comment by Flangvik** [comment]
Issue still persists, log shows "searching" but no items are matched nor fected for download.

**Comment by matthewcky2k** [comment]
@RuudBurger can this get a merge? thanks in advance!

**Pull request merged**
