### PR TITLE
New HTTPS URL

### PR DESCRIPTION
**Pull request by grizzlymannn**
### Description of what this fixes:
...

### Related issues:
...

PTP is moving everything to just https://passthepopcorn.me.

### CODE REVIEW

**Comment by lattedesu** [comment]
I've already opened a pull request days ago regarding this: https://github.com/CouchPotato/CouchPotatoServer/pull/7138

**Comment by lattedesu** [comment]
I've already opened a pull request days ago regarding this issue: https://github.com/CouchPotato/CouchPotatoServer/pull/7138

**Comment by grizzlymannn** [comment]
Sorry I'm new to using Github, didn't know to check for that. Thanks!

**Comment by RuudBurger** [comment]
Merged #7138

**Pull request closed without merging**
