### PR TITLE
make torrentday great again

### PR DESCRIPTION
**Pull request by nikosch86**
### Description of what this fixes:
make torrentday work again with couchpotato after they changed stuff on their end

### CODE REVIEW

**Comment by r04dw4rri0r** [comment]
Im having an issue with torrentday and I cant seem to find anyone else with a similar issue:

### Steps to reproduce:
1. Use torrentday
2. profit!

### Information:
Movie(s) I have this with: 500+
Quality of the movie being searched: 1
Providers I use: TorrentDay
Version of CouchPotato: source:(CouchPotato:CouchPotatoServer master) 12ca4c22 (2018-03-31 22:29:42)
Running on: FreeNAS 11

### Logs:
```
10-25 01:58:18 INFO [hpotato.core.plugins.base] Opening url: post https://torrentday.eu/torrents/, data: ['username', 'submit.x', 'password', 'submit', 'submit.y'] 
10-25 01:58:18 ERROR [edia._base.providers.base] Failed to login TorrentDay: Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 161, in login
    output = self.urlopen(self.urls['login'], data = self.getLoginParams())
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/base.py", line 220, in urlopen
    response = r.request(method, url, **kwargs)
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/adapters.py", line 371, in send
    timeout=timeout
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/packages/urllib3/connectionpool.py", line 533, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/packages/urllib3/connectionpool.py", line 239, in _get_conn
    conn.close()
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/httplib.py", line 801, in close
    self.sock.close()   # close it manually... there may be other refs
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/packages/urllib3/contrib/pyopenssl.py", line 213, in close
    return self.connection.shutdown()
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1522, in shutdown
    self._raise_ssl_error(self._ssl, result)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (32, 'EPIPE')
 
10-25 01:58:18 ERROR [edia._base.providers.base] Failed to login to: TorrentDay 
```

**Comment by Jbekker** [comment]
Tested this manually, searching TorrentDay actually works again after this change.

**Comment by skar4242** [comment]
Same for me. CP now works fine with TorrentDay again.

**Comment by skar4242** [comment]
I'm getting this: 
ERROR[edia._base.providers.base] Failed to login to: TorrentDay

I've done a clean install and have the latest version. Checked my settings including the Cookie data. Cant get it to work. I've messaged the TD site admins to see if they've made any changes that could be causing this. Is anyone else having this problem? Or is it me?

**Comment by Jbekker** [comment]
I thought it was just me, I guess not!

**Comment by skar4242** [comment]
No. I had it working with this fix. This is new. Got a reply from the site. Their stance is that they wont support third party apps. Even though I asked if they'd made an changes to their site and I didnt ask for help with CP. Anyway, it looks like it's to do with the login page. When CP goes to www.torrentday.com/t it resolves to www.torrentday.com/login.php this brings up the standard login and reCaptcha box. So for some reason it's not getting past that. Do you the string thats created by CP to autologin and get around the reCaptcha? I've got my cookie details in but I dont know how it gets sent.

**Comment by skar4242** [comment]
OK it's working again. This isnt a CP problem. Its the site. That was frustrating to say the least.

**Comment by anderwm** [comment]
This still work for you? I get failed to log in

**Pull request merged**
