### PR TITLE
Suppress "Before ETA" notifications when "Always search" is disabled

### PR DESCRIPTION
**Pull request by ellismichaelc**
Addresses issues: #4312, #4876

It's ridiculous this hasn't been fixed several YEARS ago. Several issues in the past have been closed with excuses such as "These notifcations are there for a reason. You will keep getting them until you select a release manually or ignore the releases (if they're false positives)." - The notifications are simply there to remind me that there's a dashboard. Thanks.

It is absolutely unacceptable when the 'always search' option is off, to spam my users with this:
```[12:01]
Found 246 releases for "10 Cloverfield Lane" before ETA. Select and download via the dashboard.

[12:01]  
Found 75 releases for "X-Men: Apocalypse" before ETA. Select and download via the dashboard.

[12:01]  
Found 236 releases for "London Has Fallen" before ETA. Select and download via the dashboard.

[12:02]  
Found 69 releases for "Captain America: Civil War" before ETA. Select and download via the dashboard.

[12:02]  
Found 86 releases for "The Huntsman: Winter's War" before ETA. Select and download via the dashboard.

[12:02]  
Found 81 releases for "Warcraft" before ETA. Select and download via the dashboard.

[12:03]  
Found 146 releases for "Midnight Special" before ETA. Select and download via the dashboard.

[12:03]  
Found 103 releases for "Kill Command" before ETA. Select and download via the dashboard.

[12:03]  
Found 35 releases for "The Jungle Book" before ETA. Select and download via the dashboard.

[12:03]  
Found 181 releases for "Whiskey Tango Foxtrot" before ETA. Select and download via the dashboard.

[12:04]  
Found 66 releases for "Batman v Superman: Dawn of Justice" before ETA. Select and download via the dashboard.

[12:04]  
Found 195 releases for "Eddie the Eagle" before ETA. Select and download via the dashboard.

[12:04]  
Found 182 releases for "Hail, Caesar!" before ETA. Select and download via the dashboard.

[12:05]  
Found 210 releases for "Ride Along 2" before ETA. Select and download via the dashboard.

[12:05]  
Found 214 releases for "The Finest Hours" before ETA. Select and download via the dashboard.

[12:05]  
Found 32 releases for "The Do-Over" before ETA. Select and download via the dashboard.

[12:06]  
Found 1 releases for "Neighbors 2: Sorority Rising" before ETA. Select and download via the dashboard.

[12:06]  
Found 74 releases for "Never Back Down: No Surrender" before ETA. Select and download via the dashboard.

[12:07]  
Found 207 releases for "How to Be Single" before ETA. Select and download via the dashboard.

[12:07]  
Found 1 releases for "Les Tuche 2 : Le Rêve Américain" before ETA. Select and download via the dashboard.

[12:08]  
Found 27 releases for "The Angry Birds Movie" before ETA. Select and download via the dashboard.
```

### CODE REVIEW

**Comment by RuudBurger** [comment]
Thanks for the PR, but something went wrong and it contains to much commits (merging develop from master?) So I can't merge this
I think you are correct that the messages should stop, but I think it's better to add an option to disable the ETA messages, then your current solution.

**Comment by ellismichaelc** [comment]
You've got to be joking. Here's a fix to a problem many of your users have, and you choose to ignore it because you think you have a better solution -- but won't work on it for what? Another 4 years?

This is why couchpotato is borderline unusable. And there will be a suitable replacement soon.

**Comment by maxcore** [comment]
Thx for this !!

**Comment by sjlu** [comment]
@ellismichaelc all he's asking you is to rebase your commits? (1) and add a second option to disable those messages on top of the always search option in case someone wants them.

**Pull request closed without merging**
