### PR TITLE
Fixing Torrentleech with new interface based on JS and json

### PR DESCRIPTION
**Pull request by pheuzoune**
### Description of what this fixes:

Fix TorrentLeech provider : New interface is based on JS and json. 
Rebuild the  _searchOnTitle function to use new URL format and json result.

### CODE REVIEW

**Comment by ensignvorik** [comment]
Thank you for this, hope it can get merged ASAP.

**Comment by ensignvorik** [comment]
Can anyone get this one pushed through please?

**Comment by norrgrd** [comment]
I've made these changes myself and it works perfectly but now there's another issue related to CloudFlare (I'm guessing) so while this, specific fix, works it won't work anyway.

**Comment by amankapur** [comment]
Please get this through. Awaiting eagerly..

**Comment by CrazyMacGuy** [comment]
The SickRage team ran into issues as well, it appears that the calls they were using and working with the new Cloudflare pieces of TorrentLeech required NodeJS to be installed. Just thought I'd add that information to the conversation, and I'll be making the same manual changes above to my system to validate if those changes plus the presence of NodeJS will work properly.

**Comment by norrgrd** [comment]
I've already tried that. Both with nodejs and legacy version. Does not help. It works perfectly for SickRage though. 


Skickat från min mobiltelefon. Vänligen ha överseende med eventuella felstavningar och korta svar.
-------- Original message --------From: CrazyMacGuy <notifications@github.com> Date: 02/05/2018  08:31  (GMT+01:00) To: CouchPotato/CouchPotatoServer <CouchPotatoServer@noreply.github.com> Cc: norrgrd <norrgrd@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [CouchPotato/CouchPotatoServer] Fixing Torrentleech with new interface based on JS and json (#7276) 
The SickRage team ran into issues as well, it appears that the calls they were using and working with the new Cloudflare pieces of TorrentLeech required NodeJS to be installed. Just thought I'd add that information to the conversation, and I'll be making the same manual changes above to my system to validate if those changes plus the presence of NodeJS will work properly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CouchPotato/CouchPotatoServer","title":"CouchPotato/CouchPotatoServer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CouchPotato/CouchPotatoServer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CrazyMacGuy in #7276: The SickRage team ran into issues as well, it appears that the calls they were using and working with the new Cloudflare pieces of TorrentLeech required NodeJS to be installed. Just thought I'd add that information to the conversation, and I'll be making the same manual changes above to my system to validate if those changes plus the presence of NodeJS will work properly. "}],"action":{"name":"View Pull Request","url":"https://github.com/CouchPotato/CouchPotatoServer/pull/7276#issuecomment-385877713"}}}

**Comment by CrazyMacGuy** [comment]
Yup, confirmed here as well - here are the error log outputs from my system: 

```
05-02 02:32:46 ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentLeech: https://www.torrentleech.org/user/account/login/ Traceback (most recent call last): HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://www.torrentleech.org/user/account/login/
05-02 02:32:46 ERROR
[ couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last): File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler return handler(*args, **kwargs) File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 219, in search if self.urls.get('login') and not self.login(): File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 181, in login if self.login_fail_msg and self.login_fail_msg in output: UnboundLocalError: local variable 'output' referenced before assignment encoding=UTF-8 debug=False args=['--data_dir', '/var/db/couchpotato', '--pid_file', '/var/run/couchpotato/couchpotato.pid', '--daemon'] app_dir=/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer data_dir=/var/db/couchpotato desktop=None options=Namespace(config_file='/var/db/couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/var/db/couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=False)
```

**Comment by ensignvorik** [comment]
Theres a suggestion in the CP forums that changing the URL to the old v4 site works?

Haven't tried editing it myself to see if it works?

urls = {
'test': 'https://v4.torrentleech.org/',
'login': 'https://v4.torrentleech.org/user/account/login/',
'login_check': 'https://torrentleech.org/user/messages',
'detail': 'https://v4.torrentleech.org/torrent/%s',
'search': 'https://v4.torrentleech.org/torrents/browse/index/query/%s/categories/%s',
'download': 'https://v4.torrentleech.org%s',
}

**Comment by BallzOfCheeze** [comment]
Was wondering if there is a fix for this issue.
As the fix ensignvorik suggested didn't do anything for me.

I think this issue might be related to cloudflare and the way to bypass there anti bot thing.
Sickrage seems to have gotten passed it [https://github.com/SickRage/SickRage/compare/1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4...a7602639bd525f27475f1eeb2fc504111a14b51c](url)

I have yet to find a way around the issue, but I am trying my best to help out.

this is the output of my error.
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: source:(CouchPotato:CouchPotatoServer master) 12ca4c22 (2018-03-31 22:29:42)
Running on: ...

### Logs:
```
05-13 22:30:44 ERROR [edia._base.providers.base] Failed to login TorrentLeech: Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 161, in login
    output = self.urlopen(self.urls['login'], data = self.getLoginParams())
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/base.py", line 226, in urlopen
    response.raise_for_status()
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://www.torrentleech.org/user/account/login
```
Has anyone gotten away around it yet?

**Comment by ensignvorik** [comment]
I finally got round to editing the file as per the suggesstion in the CP forums to edit the torrentleech.py file lines 15 - 22 with the following does indeed work. Just snatched Tomb Raider.

urls = {
'test': 'https://v4.torrentleech.org/',
'login': 'https://v4.torrentleech.org/user/account/login/',
'login_check': 'https://torrentleech.org/user/messages',
'detail': 'https://v4.torrentleech.org/torrent/%s',
'search': 'https://v4.torrentleech.org/torrents/browse/index/query/%s/categories/%s',
'download': 'https://v4.torrentleech.org%s',
}

**Comment by smorison** [comment]
Awesome, when can this be released?

**Comment by xblackw0lfx** [comment]
since I didn't get any new updates on this issue I fixed the problem myself in my CP installation doing what @ensignvorik sugested:

class Base(TorrentProvider):

    urls = {
        'test': 'https://v4.torrentleech.org/',
        'login': 'https://v4.torrentleech.org/user/account/login/',
        'login_check': 'https://torrentleech.org/user/messages',
        'detail': 'https://v4.torrentleech.org/torrent/%s',
        'search': 'https://v4.torrentleech.org/torrents/browse/index/query/%s/categories/%s',
        'download': 'https://v4.torrentleech.org%s',
    }

it works perfectly!!

Thanks!

**Comment by Speaktomenow** [comment]
I'd hoped this would fix my issue with CP, TL and Jackett...sadly it has not. It constantly times out, I think from the CloudFlare DDoS.

I've tried it with V4 and with the usual URL.

[hpotato.core.plugins.base] Failed opening url in TorrentLeech: https://www.torrentleech.org/user/account/login/ Traceback (most recent call last):
HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://www.torrentleech.org/user/account/login/

Neither does Jackett: 

[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://localhost:9117/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt5834262&user=&passkey=xxx&user=&passkey=xxx

Kind of annoying, not sure if it's Jackett, CP or TL who is to blame.

**Comment by siddadav** [comment]
will this ever be released?

**Comment by knepe** [comment]
Any fix for the Cloudflare issue where the login method gets a 503 http error? They have Cloudflare activated for both v4 and the normal url now. Before I don't think they had it for v4, that's why the fix above worked, but it doesn't now ☹️

**Comment by ThomasDevOps** [comment]
I've tried to edit the file myself. But i reverted to the original file but now Torrentleech is missing from my provders list ... Someone any idea please?

because now log says : 08-09 22:43:22 ERROR
[core.media._base.searcher] There aren't any providers enabled for your downloader (torrent,torrent_magnet,torrent,torrent_magnet). Check your settings.

And torrentleech disappeared in the settings

**Comment by ThomasDevOps** [comment]
Hello, i've tried to copy ensignvorik urls into the file. Implemented this pull request manually to my code + ensignvorik url's but also no success.

Getting this in the logs: 08-09 23:07:23 INFO
[core.media.movie.searcher] Search for Incredibles 2 in 1080p ignoring ETA
08-09 23:07:23 ERROR
[edia._base.providers.base] Failed to login TorrentLeech: unknown
08-09 23:07:23 ERROR
[edia._base.providers.base] Failed to login to: TorrentLeech
08-09 23:07:23 ERROR
[edia._base.providers.base] Failed to login TorrentLeech: unknown
08-09 23:07:23 ERROR
[edia._base.providers.base] Failed to login to: TorrentLeech


Someone can help me please? :) thank you in advance

**Comment by jeffyor** [comment]
could this package be used as a possible solution?
https://github.com/Anorov/cloudflare-scrape

**Comment by Speaktomenow** [comment]
I am not sure - but cloudflare has killed TL and Jackett interaction completely with CouchPotato. I am not sure which to give up on first: CP or TL. I have told the mods at TL about this and as many of you may know, they are _brutal_ when it comes to criticism. There's almost no point me using TL anymore if they persist with this, and when it comes to CP, there doesn't seem to be support or a work around so something has to give.

**Comment by ThomasDevOps** [comment]
But everything still works on Sickrage.. i also use torrentleech there to snatch tv show episodes. No problems there ..

**Comment by ensignvorik** [comment]
Agree this can be fixed. I am no code junkie however, but must be someone out there who loves this project enough to help fix it. 

As @knepe has mentioned they have now rolled out cloudflare to the v4 site as well, so my previous fix, no longer works.

As @ThomasDevOps mentioned, sickrage is fine, also according to TL forum, jackett is also fixed (that may have changed since this post: http://forums.torrentleech.org/index.php?/topic/37823-cardigann-jackett-indexers-no-longer-working/page__view__findpost__p__296910

What does annoy me about the TL devs is that they refuse to take responsibility as @Speaktomenow has mentioned. They just pass the buck to all the scraping tools. To be honest, I'm amazed more people haven't complained, surely they have lost loads of VIP members over this, potentially without even realising as they will have just left the site. They think they are doing us a favour, but there must be actually paying customers that have left over this, and they don't seem to be able to get that round their heads. Probably because I'm not VIP myself. Luckily I do have other sites I can use, and as others have said, it's now TL I'm losing my patience with more, but I still hold out someone can fix this.

Does a new topic need starting somewhere where we can actually get some of the main devs attention, as they seem to be ignoring this one despite all the comments?

**Comment by Speaktomenow** [comment]
Yes I agree, Sonarr handles TL calls to Jackett fine.

**Comment by Speaktomenow** [comment]
I’m a paying vip at TL, and I’m close to giving it up for just Usenet because of this.

**Comment by ThomasDevOps** [comment]
In not a python developer but cant we check sickrage what torrentleech url they are using to login. 

Once we get logged in we will try to figure out the rest like search etc

**Comment by knepe** [comment]
FYI latest Jackett works for me.

**Comment by Speaktomenow** [comment]
I have the latest Jackett and CP. Neither native TL account or Jackett work for queries from CP.

What’s your config, because it’s not working for any of us.

**Comment by knepe** [comment]
Hm ok, well the only search provider I have in CP is TorrentPotato with my Jacket API key and host. In Jackett I only added TL as normal. There's no other configuration there.

**Comment by ThomasDevOps** [comment]
I dont really know what jackett is. I just fill in my torrentleech credentials straight into CP

**Comment by knepe** [comment]
Yes, that TL provider in CP is broken right now, so as a workaround you can use Jackett which is a service for pulling torrents from different sources such as TL. Then you can set up CP to pull the torrents from Jackett with TorrentPotato provider in CP. This works for me at least, but not for some it seems. This is only a workaround for me until TL gets fixed in CP

**Comment by ThomasDevOps** [comment]
Aaah oké thanks for the explanation ! I also want to fix TL in CP itself instead of searching for (temp) workarounds. 

Im i wrong to think that its only the urls that are wrong? (Like login url and search url)

**Comment by Speaktomenow** [comment]
@knepe - using Jackett to pull results from TL works fine for me with Sonarr, not so with CP.
TL and Jackett fail to get past that cloudflare URL in CP for me. Jackett is indeed working fine, and talks to Sonarr fine...It's CP that is the problem. I don't know why, as Jackett works fine, and Sonarr seems to be able use Jackett just fine.

Jackett Error in CP: 
ERROR:[hpotato.core.plugins.base] Failed opening url in TorrentPotato _(The Jackett Feed is called Torrent Potato FYI)_

Native TL log in error:
ERROR:[hpotato.core.plugins.base] Failed opening url in TorrentLeech

**Comment by knepe** [comment]
@Speaktomenow if it works in Sonarr but not in CP then there is probably a configuration issue in your CP setup? Because Jackett is an independent service, the only thing it knows is scraping TL and that seem to work? (You can test that in your Jackett UI)

**Comment by Speaktomenow** [comment]
Yes it’s got me stumped. But it’s CP specific and since the TL CloudFlare issue.

Jackett seems to know how to report and deliver perfectly for sonarr. But CP shows log errors on both fronts that never existed before and are not the result of config issues.

As you say, the CP Jackett config is really only to point CP at Jackett. 

But Jackett and native TL config both fail in CP. 

And only CP. 

Jackett is fine, and so is sonarr.

**Comment by knepe** [comment]
@Speaktomenow have you tried disabling the original TL provider in CP and only run TorrentPotato?

**Comment by Speaktomenow** [comment]
@knepe You know what I didn't even think of that! I just tried it. I REALLY hoped that would work. 

It didn't.

**Comment by smorison** [comment]
I’m a paid user as well… perhaps we should do a poll and find out how many people they’ll lose…

Btw anyone that knows some mods on another site that works, I’m sure there are a bunch of us who would happily move and support another site 😊

**Comment by ThomasDevOps** [comment]
I thought sonarr was only for music albums. I will take a look at radarr tomorrow for my movie needs! I going to keep using sickrage for tv thou, works awesome !

**Comment by Speaktomenow** [comment]
Sonarr is for tv only. I prefer it over sickrage by a long way. 

I guess the migration path is slightly slower if you need to learn a new app, but for me as a Sonarr user, it was a pretty fast and easy process to ditch CP and move to Radarr.

I just needed the motivation (and the TL/Jackett issue was the last straw) and an hour or so of free time.

Yesterday was it for me, and I haven’t looked back. Strong app support from the dev on reddit too - always a plus!

**Comment by nodupe** [comment]
Hi @Speaktomenow - I am following your lead on this one. Just installed Raddar. Are you using it with Jacket or TL directly (it seems not to be there AFAIK)?

**Comment by ThomasDevOps** [comment]
oke maybe ill check it out. Why maybe ? Because I hate te extra Jackett step ...

If I move my setup to another tool should I then use Sonarr or Radarr? :) (pro's- and con's-wise)

**Comment by Speaktomenow** [comment]
Sonarr only does tv, so it’s not a couch potato replacement.

Radarr is based on Sonarr but for movies, so it is a couch potato replacement.

So it’s side by side really. Sonarr for tv, Radarr for movies.

If you have another solution for tv like sickbeard or sickrage then you don’t need Sonarr. However I rate Sonarr very highly, and as I was already very used to it and comfortable with it, moving from Couch Potato to Radarr was very very easy for me.

Couch Potato has been old for years, with no support and no updates. This issue was the last straw, and the push I needed.

If it ever gets an update I might come back, but I’m so familiar with Sonarr for my tv shows it was pretty easy to set up Radarr for movies.

Same underlying software, which means if you know one it won’t take any time to pick up the other.

Your call but if you’re feeling like it’s time to move, and you already know Sonarr it’s a no brainer. Super easy and it just works.

Jackett is a 90 second installation and set up, so for me I’ve got everything running the way it should be: automatically and with almost zero touch maintenance once you add a wanted movie.

From that point the next thing I have is a notification from Plex saying it’s been downloaded, decompressed, moved to my NAS and ready for watching.

Anyway, rant over. Just flagging for anyone who’s sick of CP, and feels like it’s too hard to move - it ain’t!

**Comment by Speaktomenow** [comment]
Yeah good point, your mileage may vary as the only thing running on my NAS is Plex and I’m running FreeNas on an ageing HP Proliant. The NAS really only does the storage and the streaming/transcoding.

I use a Mac for running mono, Jackett, Sonarr, SABnzbd and Transmission, and they search and download onto the nas. 

I’ve never really noticed any issues with RAM to be honest. My biggest issue is terrible internet speeds, not RAM or CPU on either the Mac or the nas.

**Comment by ensignvorik** [comment]
@ThomasDevOps sure send me an email from a valid address that you will use to sign up to IPTorrents too, to the below address:

ThomasDevOps.2.ensignvorik@spamgourmet.com (this is a self destructing email address purely for posting on here to protect my primary address)

If you can keep ratio on TL, you shouldn't have any issues on IPT, I'd recommend however you start of with some freeleech stuff to build up the ratio as obviously if you're using CP to grab BluRay ripps then you know how big those files can be, there's actually a setting in CP in the IPT section to also only grab freeleech stuff if you don't want to risk CP grabbing tonnes of stuff and crapping out your ratio.

You also get 'points' for seeding things which you can trade for upload credit, so if you seed stuff for a month, then this will also help you build up your upload credit to get going. Which I guess is the only downside to starting fresh on a new site.

What I was doing was flipping between IPT and TL on CP, and then whichever one grabbed the film, I'd also seed back to the the other tracker as long as the release was the same (correct amount of rar files etc) so if you have stuff still seeding from TL, find the torrent on IPT, download it, point it to the same location and it should also start seeding it, (dead pool 2 and avengers infinity wars for example would be good ones to outside seed if you have them from TL)

Anyway, don't want to teach you to suck eggs, I'm sure you understand all the above. 

Just check you can access iptorrents.com as it's blocked in many countries, if you have access to a VPN or whatever then should be no issue.

**Comment by ThomasDevOps** [comment]
yes im aware of the difficulites of starting at a new private torrent site. But im only gonna download movies from IPT then (not TL because its broken). And I should snatch it pretty quickly when it's release so I should get some upload going to get some ratio. (i hope...)

Good that I can trade uploadtime into uploadcredits, good to know thanks ! 
Ill send the email now.

**Comment by ensignvorik** [comment]
@ThomasDevOps done.

Yes, TV episodes, never really seed very well due to their limited lifespan ad everyone grabbing them quite quickly, I tend to just use piratebay and rarbg in sickrage for those, which work perfectly fine in sickrage. (rarbg may even work perfectly well still in CP, not tried for a while)

**Comment by ThomasDevOps** [comment]
i don't really like using public trackers, don't know why but yeah ... thats just me :p

**Comment by ensignvorik** [comment]
I'm the same, and wouldn't if I wasn't able to use my NAS behind a VPN, so the torrent client has the IP of the VPN. I also only set public trackers up to only ratio to 0.10 in SR & CP before stopping seeding, naughty I know, but usually plenty of seeds anyway, where as privates I set up to seed until I manually remove them from the client.

**Comment by ThomasDevOps** [comment]
awesome im gonna manually start some freeleech download tasks and let them upload for a while untill I have some ratio. Then Im gonna fill in my IPT info in CP and see how it goes. Thanks for the invite ! :)

**Comment by ensignvorik** [comment]
No worries, a good test once you add your details to CP would be to see whats in freeleech, add that movie to your wanted in CP, check the only use freeleech tick box under IPT settings in CP, and ensure CP snatches it, then you know it's working, without damaging your ratio.

**Comment by ThomasDevOps** [comment]
yes i could do that. But i don't think it will snatch anything since the movie has to be in "My Movies to download" list in CP, AND be a freeleech on IPT which sounds like I have a better chance of winning the lottery :)

**Comment by ensignvorik** [comment]
Use the filters in the browse section to highlight freeleech and 1080p then sort by seeds or leechers to find what the most popular stuff is, and add it into my movies in CP and it should grab it! :)

**Comment by ThomasDevOps** [comment]
yeah or just download it manually to my synology download client :) , which is what I do know. I filter on freeleech, take the last (non-pron) torrents and download them to my synology to seed

**Comment by ensignvorik** [comment]
Enjoy! :)

**Comment by nodupe** [comment]
Hi guys,
I'd love the invite @ensignvorik ! If still on, please send to cp.5.nodupe@spamgourmet.com! I'm having some problems with the Raddar configuration, since my setup involves torrenting in one server, copying the files to another server, and only then pulling the files to be locally processed. The ability to do that made me in the past leave Sonnar and go for Medusa for TV. Jacket solution is also not working on CP.

Thanks in advance

**Comment by nodupe** [comment]
Ok. I found a temporary solution that is using a mix of raddar/CP/Jacket. I configured all in a way that Raddar gets the list of my wanted movies from Couchpotato, contacts Jacket. Jacket searchs TL and sends the available files to my torrent client. CLient downloads the files on the remote server. When download is completed, those files are then copied to the final processing destination, where CP monitors a folder, process the files and places them on the right place to be digested by Plex.

Awkward as it may seem, this solution is working pretty well up to now. 

I hope CP will overcome the TL cloudfare soon, so I can dismiss Raddar and Jacket, to reduce complexity.

Thanks!

**Comment by smorison** [comment]
I run SR  and now Radar previously CP on my sinology NAS, as well as Plex and some other bits and pieces in docker containers that I spin up as required. It has 4GB RAM and about 12TB of storage in it. We routinely run 2 x 1080 channels at home and it works well… granted I went a bit overkill and have 256GB SSD for read caching and the NAS has inbuilt transcoding.

Awesome home setup and when I’m traveling (all the time) Plex is my best friend.

**Comment by ensignvorik** [comment]
@nodupe I've sent you an IPT invite to your none spam address! 

I am now out of invites, so please no more requests. Sorry.

I have also reached out the dev who added the code for sickrage to work with TL using the cfscape code, as I have no idea how to implement into CP myself. Hopefully he will respond and we can then at least manually update the necessary files to fix it ourselves until someone is happy to merge it into masterbranch.

**Comment by CrazyMacGuy** [comment]
If it helps any Developer finish this work, I also have two TL invites I can offer up... I'm half tempted to put a bug bounty on this, because I really want CP up and running again for my movies feed. I'd be willing to actually pay any developer who completes these changes a $50 💰 bounty, if that sweetens the pot? So a TL invite and $50 if you can patch this to a working state again. 

Please, only contact me if you are an actual developer, don't beg for invites. 👍

**Comment by Speaktomenow** [comment]
Or save the money, migrate to Radarr and chuck $50 towards the dev there?
:-)
Just sayin’, Couch Potato feels pretty deprecated in comparison. Jackett and TL are all working fine for me in Radarr. No Regrets.

I really liked Couch Potato, but eh...whatever gets the job done. 
:)

**Comment by CrazyMacGuy** [comment]
> Or save the money, migrate to Radarr and chuck $50 towards the dev there?

Oh, you're not wrong @Speaktomenow - but my laziness is sometimes more powerful than my desire to setup a new jail and migrate...

**Comment by norrgrd** [comment]
Getting rather frustrating this. I've tried the jackett solution but it gets so many false hits, for example see below. Anybody know of any way to tweak how jackett searches?

image

**Comment by Speaktomenow** [comment]
Oh I’ve given up, moved over to Radarr and I’m very content.

A fix won’t get me to reinstall CouchPotato now - not that you’ll ever get one.

For the benefit of those arriving via search looking for answers:

There is no fix.
Give up on Couch Potato and move on to Radarr.

**Comment by ThomasDevOps** [comment]
Couchpotato with IPtorrents provider also works very well ! So thats why im keeping CP otherwise i would have also moved to Radarr :)

**Comment by piotrasd** [comment]
how you setup CP on Radarr ? there is no support or i missed something :/

**Comment by lusidd1** [comment]
Adding the [cloudflare-scraper package](https://github.com/Anorov/cloudflare-scrape) and then replacing the [default session](https://github.com/CouchPotato/CouchPotatoServer/blob/master/couchpotato/runner.py#L157) (don't forget to `import cfscrape` at the top) with `session = cfscrape.create_scraper()` allows me to use the TorrentLeech provider again in CouchPotato. 

The caveat here is that cloudflare-scraper has a [dependency](https://github.com/Anorov/cloudflare-scrape#dependencies) on `node` being installed and on the PATH.  In the container that I run CP this required that I `apt install nodejs-legacy`.

**Comment by tvann2182** [comment]
Well it looks like IPTorrents is now doing the same thing that TL was doing. anyone got a fix for that issue?

**Comment by ensignvorik** [comment]
Switch to radarr and configure with jackett like the rest of us have done. Can confirm that works for both iptorrents and torrentlee h

**Comment by jmirodrigues** [comment]
Hi,

Where it says: torrentleech.org i've replaced it by: torrentleech.cc

This torrentleech.cc doesn't use cloudflare protection, so it works ok on CP

**Pull request merged**
