### PR TITLE
Fix Transmission not reading correct status

### PR DESCRIPTION
**Pull request by fernandog**
Seeding status is 6. Not 16

### CODE REVIEW

**Comment by fernandog** [comment]
Seed is not complete right? Someone change to 16 on purpose?

**Comment by RuudBurger** [comment]
Shouldn't the whole line be remove then? Because it isn't "completed" when it's seeding.

**Comment by fernandog** [comment]
I did some tests and also need to check isFinished because it set this when seeded completed. If seeded is not compleded but torrent is completed and paused it would wrong remove it.

**Comment by fernandog** [comment]
removed that line and added the `isFinished` check

**Comment by fernandog** [comment]
@RuudBurger not interested?

**Comment by fernandog** [comment]
@RuudBurger can you please at least reply something?

**Pull request merged**
