### PR TITLE
SubsCenter service now supports the new API.

### PR DESCRIPTION
**Pull request by ofir123**
### Description of what this fixes:
This PR fixes the SubsCenter subtitles plugin, so it'll work with the new API.

### Related issues:
...

### CODE REVIEW

**Comment by siddadav** [comment]
how do i report issues. im getting this

 ### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) 711310d0 (2017-03-27 11:55:38)
Running on: ...

### Logs:
```
04-27 18:53:04 ERROR [edia._base.providers.base] Failed downloading from TorrentLeech: Traceback (most recent call last):
  File "/apps/couchpotato/couchpotato/core/media/_base/providers/base.py", line 196, in loginDownload
    return self.urlopen(url)
  File "/apps/couchpotato/couchpotato/core/plugins/base.py", line 220, in urlopen
    response = r.request(method, url, **kwargs)
  File "/apps/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/apps/couchpotato/libs/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/apps/couchpotato/libs/requests/adapters.py", line 413, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
 
```

**Comment by ofir123** [comment]
How is this related to the PR?

**Comment by ward0** [comment]
@ofir123 people can't make issues anymore so they try trough PR's.. @RuudBurger  will just ignore them since he closed the issue tab :)

**Comment by RuudBurger** [comment]
Thanks for the PR!

@siddadav Yeah I closed the issue tab and I don't have time for fixes, sorry

**Pull request merged**
