### PR TITLE
fix 2 issues with bit-hdtv

### PR DESCRIPTION
**Pull request by cjnatan**
### Description of what this fixes:
...

### Related issues:
...

issue 1: torrent details arent populated due to error in torrent id and therefore generates errors
issue 2: 'url' result is missing full url which also generates errors

### CODE REVIEW

**Comment by cjnatan** [comment]
FYI Your link is broken: https://github.com/CouchPotato/CouchPotatoServer/blob/develop/contributing.md#pull-requests

**Comment by matteraByte** [comment]
Fix was merged into Develop branch about a week ago. Still waiting on main branch release. https://github.com/CouchPotato/CouchPotatoServer/commit/1bef4dd61a8be31b9e22dd1d4a123676e31f5948

**Comment by RuudBurger** [comment]
Please wait for develop to be merged in master. Will do it soon

**Comment by ward0** [comment]
@RuudBurger Just putting a simple comment : 'Thank you!'

**Pull request closed without merging**
