### PR TITLE
Increase Default Video Sizes - HDTS, HDCAM Never Downloads

### PR DESCRIPTION
**Pull request by d8ahazard**
I have been trying to figure out why HDTS and HDCAM files wouldn't
download, despite everything appearing to work properly.  This is the
problem.  Scene filesizes for TS/CAM may match the defined sizes, but
HDTS and HDCAM files are naturally larger.

If it's not ideal to increase default sizes for defined names, then
maybe HDTS and HDCAM should have their own definitions - although this
may conflict with TS/CAM?

### Description of what this fixes:
HDTS and HDCAM files were never found by the searcher.

### Related issues:
...

### CODE REVIEW

**Comment by d8ahazard** [comment]
@CouchPotatoBot Done.

**Comment by RuudBurger** [comment]
You can change the sizes in setting for you local install. No need to edit the source for this. Unless it would benefit all, but CAM and other lower quality releases don't benefit anyone ;)

If you still want me to merge this, please provide it forked from the develop branch, so I can have look at the actual changes without all the commits from previous years. Thanks!

**Comment by d8ahazard** [comment]
I understand that CAM/TS aren't the most desirable releases for most people, but these releases are still out there, and it drove me *nuts* trying to understand why the app wouldn't download files that matched the search filters.  And honestly, *some* HD-CAM or HD-TS releases are fairly watchable these days.

I'll pull from dev, re-submit without all the noise - I admit - I pulled from master for my initial mods, then realized I should have been pulling from dev...

**Comment by d8ahazard** [comment]
Resubmitted as #7230

**Pull request closed without merging**
