### PR TITLE
deluge v2 support

### PR DESCRIPTION
**Pull request by MrAlfabet**
### Description of what this fixes:
CP can now communicate with the Deluge V2 daemon

This was stolen from: https://github.com/clinton-hall/nzbToMedia/pull/1683/commits/ddf18e25b6e55f5367f30efbd9568f10b8c208c0#diff-0e2a32c23d0d0c6418b9c86463ebfe09

### Related issues:
...

### CODE REVIEW

**Comment by Xander567** [comment]
Hoping this can go in soon - can't get couchpotato to connect to deluge at all.

**Comment by MrAlfabet** [comment]
> Hoping this can go in soon - can't get couchpotato to connect to deluge at all.

https://github.com/MrAlfabet/CouchPotatoServer

**Comment by Xander567** [comment]
It's fine, i got your code working.

FYI, you need __init__.py in your deluge_client folder. Couldn't get it working without that.

**Comment by MrAlfabet** [comment]
But I do? https://github.com/MrAlfabet/CouchPotatoServer/tree/master/libs/deluge_client

Maybe something went wrong with the pull requests (my first time doing one). adding the __init__ file came in the same commit where I changed some more code to remove errors and get labels working. You might want to compare the master branch from my fork with my pull request here.

**Comment by Xander567** [comment]
Weird. This PR we're chatting on doesn't list the init.py file at all. Could be a .gitignore on your end?

**Comment by MrAlfabet** [comment]
That would mean it would not be in my forked repo either, which it is. I
think this pull request should link multiple commits from my fork, but it
only links the initial commit

**Comment by Xander567** [comment]
So ye, i just checked and the deluge.py file in this PR is not the same as the one on your master. CouchPotato is throwing a bunch of errors about .get()
Just replaced it with the one that is on the master branch of your repo

**Comment by MrAlfabet** [comment]
I've added the same commits to the develop branch now.

**Comment by nydave69** [comment]
Is anyone working on any of the other issues, like the 8 digit IMDB IDs..
Adding any movie that has an 8 digit ID really mess things up...
One of the things it causes is that it will match every one with UNKNOWN and then try do download anything with UNKNOWN in the title...

**Comment by Xander567** [comment]
@RuudBurger could we get an update on when some of these PR's will be merged? This one and the IMDB 8 character Id PR are both passing travis tests.

**Comment by boredazfcuk** [comment]
Hey, everyone... Any tips on how to get this working? I'm running an Alpine Linux container and applying the patch during the build like this:
```
 wget --quiet https://github.com/CouchPotato/CouchPotatoServer/pull/7311.dif
 /usr/libexec/git-core/git-apply 7311.diff
```
I can see:
```
from deluge_client.client import DelugeRPCClient
```
in deulge.py so I know it's applied properly.

The test button in CouchPotato still fails though.

Any suggestions?

**Comment by MrAlfabet** [comment]
> Any suggestions?

Try with sonarr to verify you have the right settings, and deluge set up properly.

**Comment by Xander567** [comment]
Make sure to restart CouchPotato and check to see if the pyc files were recreated. If they're timestamps haven't changed, delete the pyc files and restart - they'll be recreated.

**Comment by RuudBurger** [comment]
Thanks for the PR!

**Comment by boredazfcuk** [comment]
> Try with sonarr to verify you have the right settings, and deluge set up properly.

I've had a look at Sonarr, but I can't use it to test I have the correct settings. Like SickGear and Headphones, Sonarr connects to Deluge via the WebGUI (https://deluge:8112/deluge/ on my system). The back end code is (presumably) a lot different for both connection scenarios.

However, I have been able to test my configuration using the deluge-console application and I think it's actually a password issue with the daemon. Currently my container entrypoint script sets the WebUI password in web.conf by creating a sha1 hashed password. It uses the salt in the web.conf file and a password stored in an environment variable.

I was then creating a couchpotato user in the /config/auth file and using the hashed password. It seems that Deluge's auth file only likes plaintext passwords in this file though (even though the localclient password appears to be hashed).

**Comment by MrAlfabet** [comment]
Geen probleem!

**Comment by boredazfcuk** [comment]
It was the password issue in the end... The passwords in the deluge daemon auth file aren't hashed like they are in the web.conf file, even though they look like they are.

My Deluge container has nzbToMedia installed in it and that is working, it's using the localclient account though. When i tried the couchpotato account, it was just timing out, rather then throwing a genuine error.

It wasn't until I tried the deluge-console application, that I got a 'Bad password' error.

Thanks for the pointer. Much appreciated.

**Pull request merged**
