### PR TITLE
Add MagnetDL as Torrent provider

### PR DESCRIPTION
**Pull request by pentacruleo**
### Description of what this fixes:

Adds support for MagnetDL.

Discovered that website recently and thought it would be a great addition to the list of torrent providers!

Apologies for the duplicated PR, I made a typo on my git config username and ended messing up the history of the forked repository so much that decided to delete it and fork again.

### CODE REVIEW

**Comment by station384** [comment]
This patch works well.

**Comment by wkupike2000** [comment]
How do I get this patch applied to my CP install?

**Comment by station384** [comment]
if you use git you can have it apply this pull.   or you can do like I did (and the much less elegant way) and just copy out the files that pentacruleo added and copy them into the correct directories and restart,.  The directories are the same as check in directories.   where they are on your filesystem,  that depends on your install,  you will need to look for them.

**Comment by RuudBurger** [comment]
Thanks!

**Comment by wkupike2000** [comment]
Tech guy but complete newb to Github. I've searched and don't know how to use git or how to "apply this pull". Any instructions you can link to or share? Thanks!

**Pull request merged**
