### PR TITLE
IMDB new ID's have 8 digits"tt10432050"

### PR DESCRIPTION
**Pull request by nydave69**
### Description of what this fixes:
...

### Related issues:
...Searches fail if the id contains 8 digits
cannot add new movies if using the TTnumber in the search if it contains 8 digits
If you use the title adds but fails to search correctly.

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
Please note:

> * [ ]  Make sure you send a PR against the DEVELOP branch

**Comment by nydave69** [comment]
Is anyone updating the master with changes... looks like it been not updated since Jan 2019..
and there are a lot of issues with it..

should I be looking elsewhere for an alternative..

**Comment by nydave69** [comment]
Why doesn't this repository have an Issue section.
Just spent over an hour trying to figure out how to create a pull request..
This one I created, I got lucky after a few hours of screwing around to get it posted a few days ago.

reason I wanted to create a new one was...
The master hasn't been updated in over a year.....  There are so many things wrong with the master branch..  I spend most of the time restarting this software just to get it to run.  seems link it spawns processes to do things but they never really do anything.  A restart will list all the process it has to kill but there are like 20 for the quality check (something like that), reamer, and a slew of others..  Problem is this isn't in the logs,  logs looks like everything is fine, If I do nothing it will find nothing for weeks (that's how I found out about these problems), came back from out of town..  Restart gets it going again but doesn't last a day.

Anyone have a suggestion how to proceed?

**Comment by nydave69** [comment]
getting this error, can't figure out how to post here...

### Steps to reproduce:
1. ..normal running   think this is the IMDB 8 digit issue with New Movies
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer master) 75e576ee (2019-01-13 08:13:34)
Running on: ...

### Logs:
```
01-21 22:46:48 ERROR [   couchpotato.core.event] Error in event "automation.get_movies", that wasn't caught: Traceback (most recent call last):
  File "C:\CouchPotato\CouchPotatoServer\couchpotato\core\event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "C:\CouchPotato\CouchPotatoServer\couchpotato\core\media\movie\providers\automation\base.py", line 38, in _getMovies
    return self.getIMDBids()
  File "C:\CouchPotato\CouchPotatoServer\couchpotato\core\media\movie\providers\automation\imdb.py", line 112, in getIMDBids
    if not watchlist_enablers[index]:
IndexError: list index out of range
encoding=cp1252 debug=True args=['--debug'] app_dir=C:\CouchPotato\CouchPotatoServer data_dir=C:\Users\Plex\AppData\Roaming\CouchPotato desktop=None options=Namespace(config_file='C:\\Users\\Plex\\AppData\\Roaming\\CouchPotato\\settings.conf', console_log=False, daemon=False, data_dir=None, debug=True, pid_file='C:\\Users\\Plex\\AppData\\Roaming\\CouchPotato\\couchpotato.pid', quiet=False)  
```


system wouldn't let me create a bug report..

**Comment by RuudBurger** [comment]
It's hard to review this with it being branched from develop.

**Comment by RuudBurger** [comment]
Merged the one from @clinton-hall 
Thanks for the PR

**Pull request closed without merging**
