### PR TITLE
Automatic account disabling on login failure for all torrent providers

### LINKED ISSUE #2232: Incorrect password causes IP ban on Passthepopcorn
Could we make couchpotato quit attempting to log into passthepopcorn on incorrect password until the user does something? I changed my password on passthepopcorn and didn't think to change it in couchpotato (figured it was an api key) so I got IP banned twice before I figured out why.

### LINKED ISSUE #5033: No account info for Torrent Provider still causes site login attempt
If a Torrent Provider is enabled but no username and/or passkey information is entered CPS will still attempt to login with nothing which then triggers an IP ban.

Easily reproduced. Click on the Torrent Provider (e.g., TorrentBytes) and allow it to save.

Fix: I would suggest testing for a username and/or passkey before attempting to login. Maybe add further logic which could address Issue #2232 or at least halt when receiving HTTPError 403.

This is with the most recent Git master version (ID 2016)

Log entries:
06-06 18:47:12ERROR[edia._base.providers.base] Failed to login TorrentBytes: unknown
06-06 18:47:12ERROR[edia._base.providers.base] Failed to login to: TorrentBytes

06-06 18:47:08ERROR[hpotato.core.plugins.base] Failed opening url in TorrentBytes: https://www.torrentbytes.net/takelogin.php Traceback (most recent call last):
HTTPError: 403 Client Error: Forbidden
06-06 18:47:08ERROR[edia._base.providers.base] Failed to login TorrentBytes: Traceback (most recent call last):
  File "C:\Manually-Installed\CouchPotatoServer\couchpotato\core\media\_base\providers\base.py", line 159, in login
    output = self.urlopen(self.urls['login'], data = self.getLoginParams())
  File "C:\Manually-Installed\CouchPotatoServer\couchpotato\core\plugins\base.py", line 238, in urlopen
    response.raise_for_status()
  File "C:\Manually-Installed\CouchPotatoServer\libs\requests\models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden

### LINKED ISSUE #6228: Torrentbytes Login failed - Got Banned
### Steps to reproduce:
1. Setup my Torrentbytes login
2. Go to movies and Refresh a movie I like to (re)find

### Information:
Movie(s) I have this with: Delicatessen (but don't think that matters anyway)
Quality of the movie being searched: Any
Providers I use: Torrentbytes, RARBG
Version of CouchPotato: c4fad95c (2/24/2016, 4:05:59 PM)
Updater: git, master
ID: 13627
Running on: Synology NAS DS412+

### Logs:
`03-25 16:45:38 INFO[core.media.movie.searcher] Search for Delicatessen in 720p ignoring ETA
03-25 16:45:38 INFO[hpotato.core.plugins.base] Opening url: post https://www.torrentbytes.net/takelogin.php, data: ['username', 'login', 'password']
03-25 16:45:39 ERROR[edia._base.providers.base] Failed to login TorrentBytes: unknown
03-25 16:45:39 ERROR[edia._base.providers.base] Failed to login to: TorrentBytes
03-25 16:45:39 INFO[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: []
03-25 16:45:39 INFO[hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22delicatessen+1991%22%20size%203000m%20-%2010000m%20seed%20%3E%200, data: []
03-25 16:45:41 INFO[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=qdhuzc4m8y&mode=search&search_imdb=tt0101700&min_seeders=5&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: []
03-25 16:45:42 INFO[hpotato.core.plugins.base] Opening url: post https://www.torrentbytes.net/takelogin.php, data: ['username', 'login', 'password']
03-25 16:45:42 ERROR[edia._base.providers.base] Failed to login TorrentBytes: unknown
03-25 16:45:42 ERROR[edia._base.providers.base] Failed to login to: TorrentBytes
03-25 16:45:42 INFO[core.media.movie.searcher] Search for Delicatessen in 1080p ignoring ETA
03-25 16:45:43 INFO[hpotato.core.plugins.base] Opening url: post https://www.torrentbytes.net/takelogin.php, data: ['username', 'login', 'password']
03-25 16:45:43 ERROR[edia._base.providers.base] Failed to login TorrentBytes: unknown
03-25 16:45:43 ERROR[edia._base.providers.base] Failed to login to: TorrentBytes
03-25 16:45:43 INFO[hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22delicatessen+1991%22%20size%204000m%20-%2020000m%20seed%20%3E%200, data: []
03-25 16:45:44 INFO[hpotato.core.plugins.base] Opening url: post https://www.torrentbytes.net/takelogin.php, data: ['username', 'login', 'password']
03-25 16:45:44 ERROR[edia._base.providers.base] Failed to login TorrentBytes: unknown
03-25 16:45:44 ERROR[edia._base.providers.base] Failed to login to: TorrentBytes
03-25 16:45:44 INFO[core.media.movie.searcher] Search for Delicatessen in BR-Rip ignoring ETA
03-25 16:45:45 INFO[hpotato.core.plugins.base] Opening url: post https://www.torrentbytes.net/takelogin.php, data: ['username', 'login', 'password']
03-25 16:45:45 ERROR[hpotato.core.plugins.base] Failed opening url in TorrentBytes: https://www.torrentbytes.net/takelogin.php Traceback (most recent call last): HTTPError: 403 Client Error: Forbidden for url: https://www.torrentbytes.net/takelogin.php
03-25 16:45:45 ERROR[edia._base.providers.base] Failed to login TorrentBytes: Traceback (most recent call last): File "/volume2/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 161, in login output = self.urlopen(self.urls['login'], data = self.getLoginParams()) File "/volume2/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/base.py", line 226, in urlopen response.raise_for_status() File "/volume2/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 403 Client Error: Forbidden for url: https://www.torrentbytes.net/takelogin.php
03-25 16:45:45 ERROR[edia._base.providers.base] Failed to login to: TorrentBytes`

Hope this can be solved

Thanks a lot

### PR DESCRIPTION
**Pull request by YourHuckleberry**
### Description of what this fixes:
All torrent providers now automatically disable themselves on authentication failure. (except TorrentDay, which I plan to work on later)

fixes #2232 
fixes #6228 
fixes #5033

### Related issues:
This does not work with TorrentDay.

### CODE REVIEW

**Comment by jkaberg** [comment]
You mentioned TorrentDay, but you're also missing;
- [ ] HDAccess
- [ ] PassThePopcorn
- [ ] HD4Free

Otherwise well done!

**Comment by YourHuckleberry** [comment]
Thanks @jkaberg for the words of encouragement,

HD4free is in there.

As to PassThePopcorn & HDAccess, both of them return http status code 401 which is already handled by existing code @ base.py/line 173 in my commit.

Cheers!

**Comment by jkaberg** [comment]
Ah sorry about that, overlooked that obviously :-)

**Comment by RuudBurger** [comment]
Awesome, thanks!

**Comment by NGDM** [comment]
Please take issue 6489 into account for this feature. 
I'm getting KeyError error in the log for the HD4Free provider when checking for API key validity.
Thanks.

**Comment by ersan** [comment]
I was wondering why PTP kept getting disabled - yes can this be made smarter or made an option?

**Comment by YourHuckleberry** [comment]
PTP keeps getting disabled because their servers are not responding to the
request.

Keeping up with individual providers and their individual reactions is to
me,   beyond the intended scope of CP.

 A project called Jackett (available on Github) has been written
specifically to handle communication with providers and can made to work
with couchpotato,  and it's what I have personally done for my own CP
system to resolve these 'one off' issues.

Since moving my search requests to Jackett my system has been MUCH more
reliable.

**Pull request merged**
